version: "3"

services:
  # Label used to access the service container
  postgres:
    # Docker Hub image
    image: postgres
    # Provide the password for postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
